{
  "formatVersion": "1.1",
  "component": {
    "group": "com.android.tools.build",
    "module": "builder",
    "version": "8.7.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "manifest-merger",
          "version": {
            "requires": "31.7.1"
          }
        },
        {
          "group": "com.android",
          "module": "zipflinger",
          "version": {
            "requires": "8.7.1"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "apksig",
          "version": {
            "requires": "8.7.1"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "apkzlib",
          "version": {
            "requires": "8.7.1"
          }
        },
        {
          "group": "com.squareup",
          "module": "javawriter",
          "version": {
            "requires": "2.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "builder-8.7.1.jar",
          "url": "builder-8.7.1.jar",
          "size": 15074477,
          "sha512": "68251c26c4aee69efde3b07b2dd8276d7f81a2cc19d24fd523774e7bbcbfcab7f1d01ce4a1c0d5b1c92c7ffe7f0008f699186318d541e919d228e35b6271f1cc",
          "sha256": "4ae2cfc0dd51269e4b208482ee83c8f291e0ea487340279277e4782b7255f5b4",
          "sha1": "13558c232fdbeda4cc3cc8f120639090b182e1aa",
          "md5": "518ef3666b48299a46492fba06ec0f84"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "builder-model",
          "version": {
            "requires": "8.7.1"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "builder-test-api",
          "version": {
            "requires": "8.7.1"
          }
        },
        {
          "group": "com.android.tools",
          "module": "sdklib",
          "version": {
            "requires": "31.7.1"
          }
        },
        {
          "group": "com.android.tools",
          "module": "sdk-common",
          "version": {
            "requires": "31.7.1"
          }
        },
        {
          "group": "com.android.tools",
          "module": "common",
          "version": {
            "requires": "31.7.1"
          }
        },
        {
          "group": "com.android.tools.ddms",
          "module": "ddmlib",
          "version": {
            "requires": "31.7.1"
          }
        },
        {
          "group": "com.android",
          "module": "signflinger",
          "version": {
            "requires": "8.7.1"
          }
        },
        {
          "group": "com.android.tools.analytics-library",
          "module": "protos",
          "version": {
            "requires": "31.7.1"
          }
        },
        {
          "group": "com.android.tools.analytics-library",
          "module": "tracker",
          "version": {
            "requires": "31.7.1"
          }
        },
        {
          "group": "com.android.tools.layoutlib",
          "module": "layoutlib-api",
          "version": {
            "requires": "31.7.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.20"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcpkix-jdk18on",
          "version": {
            "requires": "1.77"
          }
        },
        {
          "group": "commons-codec",
          "module": "commons-codec",
          "version": {
            "requires": "1.10"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk18on",
          "version": {
            "requires": "1.77"
          }
        },
        {
          "group": "javax.inject",
          "module": "javax.inject",
          "version": {
            "requires": "1"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.6"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "manifest-merger",
          "version": {
            "requires": "31.7.1"
          }
        },
        {
          "group": "com.android",
          "module": "zipflinger",
          "version": {
            "requires": "8.7.1"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "apksig",
          "version": {
            "requires": "8.7.1"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "apkzlib",
          "version": {
            "requires": "8.7.1"
          }
        },
        {
          "group": "com.squareup",
          "module": "javawriter",
          "version": {
            "requires": "2.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "builder-8.7.1.jar",
          "url": "builder-8.7.1.jar",
          "size": 15074477,
          "sha512": "68251c26c4aee69efde3b07b2dd8276d7f81a2cc19d24fd523774e7bbcbfcab7f1d01ce4a1c0d5b1c92c7ffe7f0008f699186318d541e919d228e35b6271f1cc",
          "sha256": "4ae2cfc0dd51269e4b208482ee83c8f291e0ea487340279277e4782b7255f5b4",
          "sha1": "13558c232fdbeda4cc3cc8f120639090b182e1aa",
          "md5": "518ef3666b48299a46492fba06ec0f84"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "builder-8.7.1-javadoc.jar",
          "url": "builder-8.7.1-javadoc.jar",
          "size": 346021,
          "sha512": "b7685c3fec5ddddd2846cded3a39b6488e7b8e8bc5ad662a4f6dfbf6124d733b50ea50082bd43bc701d4016a49fac02503abf2cb91c1148bf955522efc9cd5a0",
          "sha256": "42140b803e391920cb8e73e6405f46faec093967335751fd66ec7c180588bef1",
          "sha1": "f53ac89cf1aac283877add48c48d7ee859273253",
          "md5": "34c85671ce4d8281c7bb190acdc9fefa"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "builder-8.7.1-sources.jar",
          "url": "builder-8.7.1-sources.jar",
          "size": 282773,
          "sha512": "2bf831e9af9620b091358227e13f8e0ab99610b421e875acf62b064be8e8b43340633ca71efe01879ac766e9f47fddfa28e742db4bbd56cb3011bf379ccc99cf",
          "sha256": "ad5257cb85d7e566cb2c220b956d83b97703523c48ef32a4eb0db2c0c8048842",
          "sha1": "91507b8d7e1761432370dace62d05ad53dd3ba17",
          "md5": "ca9bd4766650b888b641ca7372d607d9"
        }
      ]
    }
  ]
}
