{
  "formatVersion": "1.1",
  "component": {
    "group": "org.jetbrains.kotlin",
    "module": "kotlin-gradle-plugin-model",
    "version": "1.8.22",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "kotlin-gradle-plugin-model-1.8.22-sources.jar",
          "url": "kotlin-gradle-plugin-model-1.8.22-sources.jar",
          "size": 7932,
          "sha512": "33d5022df714168fb55a4745c47021948968b3123609f90c9e3659780b7c7387d4eb6a3f269c8b43438865ad7d581676952a90747b161b8135fe69015870a9e7",
          "sha256": "368bbe11831a72ba9df33f9c03c7795c967eace2bcfad0c91d406e2d9d494cd8",
          "sha1": "3eedaa08194a420cd2115833b92c97341b6aff48",
          "md5": "43536e5d73845058643dd884799797ce"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "kotlin-gradle-plugin-model-1.8.22-javadoc.jar",
          "url": "kotlin-gradle-plugin-model-1.8.22-javadoc.jar",
          "size": 261,
          "sha512": "747d2f00a7f5f379582e33e452f30f3a25732a510971d9ed5161355bf7ef0fc507fef30883960dbfc780d36b6e8215fba01086b4ee053358805686e2f2c1aa85",
          "sha256": "69e1a62e5752ca3f43fb1607f161379bbe88b64af89c1a543c126160adf7cc53",
          "sha1": "5b8f86fea035328fc9e8c660773037a3401ce25f",
          "md5": "e7e9f45eb9d74540092920528bb0abf0"
        }
      ]
    },
    {
      "name": "runtimeElementsWithFixedAttribute",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin-api",
          "version": {
            "requires": "1.8.22"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-reflect"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-script-runtime"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugins-bom",
          "version": {
            "requires": "1.8.22"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-reflect"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-script-runtime"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ],
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        }
      ],
      "files": [
        {
          "name": "kotlin-gradle-plugin-model-1.8.22.jar",
          "url": "kotlin-gradle-plugin-model-1.8.22.jar",
          "size": 12803,
          "sha512": "2d07f4b5d0fa8a160bce7b1060766145ff18c8fe057fe6e2b346edca2399ce653670cd787f15518ed9e265fdd569d1be3611e7334079f47ba7fc4064fd58f3fb",
          "sha256": "771d4ac928f422e43cf7ec067bbea337a0d2edf146389b65dda65df6d2d6e54a",
          "sha1": "3607c42ee2a7b827e978906ffc26f34c5241ae91",
          "md5": "1d16d30fc52cc0e088d47c0f15fd5fda"
        }
      ]
    },
    {
      "name": "apiElementsWithFixedAttribute",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin-api",
          "version": {
            "requires": "1.8.22"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-reflect"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-script-runtime"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugins-bom",
          "version": {
            "requires": "1.8.22"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-reflect"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-script-runtime"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ],
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        }
      ],
      "files": [
        {
          "name": "kotlin-gradle-plugin-model-1.8.22.jar",
          "url": "kotlin-gradle-plugin-model-1.8.22.jar",
          "size": 12803,
          "sha512": "2d07f4b5d0fa8a160bce7b1060766145ff18c8fe057fe6e2b346edca2399ce653670cd787f15518ed9e265fdd569d1be3611e7334079f47ba7fc4064fd58f3fb",
          "sha256": "771d4ac928f422e43cf7ec067bbea337a0d2edf146389b65dda65df6d2d6e54a",
          "sha1": "3607c42ee2a7b827e978906ffc26f34c5241ae91",
          "md5": "1d16d30fc52cc0e088d47c0f15fd5fda"
        }
      ]
    },
    {
      "name": "gradle70JavadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.plugin.api-version": "7.0",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "kotlin-gradle-plugin-model-1.8.22-gradle70-javadoc.jar",
          "url": "kotlin-gradle-plugin-model-1.8.22-gradle70-javadoc.jar",
          "size": 261,
          "sha512": "747d2f00a7f5f379582e33e452f30f3a25732a510971d9ed5161355bf7ef0fc507fef30883960dbfc780d36b6e8215fba01086b4ee053358805686e2f2c1aa85",
          "sha256": "69e1a62e5752ca3f43fb1607f161379bbe88b64af89c1a543c126160adf7cc53",
          "sha1": "5b8f86fea035328fc9e8c660773037a3401ce25f",
          "md5": "e7e9f45eb9d74540092920528bb0abf0"
        }
      ],
      "capabilities": [
        {
          "group": "org.jetbrains.kotlin",
          "name": "kotlin-gradle-plugin-model-gradle70",
          "version": "1.8.22"
        }
      ]
    },
    {
      "name": "gradle70SourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.plugin.api-version": "7.0",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "kotlin-gradle-plugin-model-1.8.22-gradle70-sources.jar",
          "url": "kotlin-gradle-plugin-model-1.8.22-gradle70-sources.jar",
          "size": 7932,
          "sha512": "33d5022df714168fb55a4745c47021948968b3123609f90c9e3659780b7c7387d4eb6a3f269c8b43438865ad7d581676952a90747b161b8135fe69015870a9e7",
          "sha256": "368bbe11831a72ba9df33f9c03c7795c967eace2bcfad0c91d406e2d9d494cd8",
          "sha1": "3eedaa08194a420cd2115833b92c97341b6aff48",
          "md5": "43536e5d73845058643dd884799797ce"
        }
      ],
      "capabilities": [
        {
          "group": "org.jetbrains.kotlin",
          "name": "kotlin-gradle-plugin-model-gradle70",
          "version": "1.8.22"
        }
      ]
    },
    {
      "name": "gradle70ApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.plugin.api-version": "7.0",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin-api",
          "version": {
            "requires": "1.8.22"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-reflect"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-script-runtime"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ],
          "requestedCapabilities": [
            {
              "group": "org.jetbrains.kotlin",
              "name": "kotlin-gradle-plugin-api-gradle70"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "kotlin-gradle-plugin-model-1.8.22-gradle70.jar",
          "url": "kotlin-gradle-plugin-model-1.8.22-gradle70.jar",
          "size": 12803,
          "sha512": "2d07f4b5d0fa8a160bce7b1060766145ff18c8fe057fe6e2b346edca2399ce653670cd787f15518ed9e265fdd569d1be3611e7334079f47ba7fc4064fd58f3fb",
          "sha256": "771d4ac928f422e43cf7ec067bbea337a0d2edf146389b65dda65df6d2d6e54a",
          "sha1": "3607c42ee2a7b827e978906ffc26f34c5241ae91",
          "md5": "1d16d30fc52cc0e088d47c0f15fd5fda"
        }
      ],
      "capabilities": [
        {
          "group": "org.jetbrains.kotlin",
          "name": "kotlin-gradle-plugin-model-gradle70",
          "version": "1.8.22"
        }
      ]
    },
    {
      "name": "gradle70RuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.plugin.api-version": "7.0",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin-api",
          "version": {
            "requires": "1.8.22"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-reflect"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-script-runtime"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ],
          "requestedCapabilities": [
            {
              "group": "org.jetbrains.kotlin",
              "name": "kotlin-gradle-plugin-api-gradle70"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "kotlin-gradle-plugin-model-1.8.22-gradle70.jar",
          "url": "kotlin-gradle-plugin-model-1.8.22-gradle70.jar",
          "size": 12803,
          "sha512": "2d07f4b5d0fa8a160bce7b1060766145ff18c8fe057fe6e2b346edca2399ce653670cd787f15518ed9e265fdd569d1be3611e7334079f47ba7fc4064fd58f3fb",
          "sha256": "771d4ac928f422e43cf7ec067bbea337a0d2edf146389b65dda65df6d2d6e54a",
          "sha1": "3607c42ee2a7b827e978906ffc26f34c5241ae91",
          "md5": "1d16d30fc52cc0e088d47c0f15fd5fda"
        }
      ],
      "capabilities": [
        {
          "group": "org.jetbrains.kotlin",
          "name": "kotlin-gradle-plugin-model-gradle70",
          "version": "1.8.22"
        }
      ]
    },
    {
      "name": "gradle71JavadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.plugin.api-version": "7.1",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "kotlin-gradle-plugin-model-1.8.22-gradle71-javadoc.jar",
          "url": "kotlin-gradle-plugin-model-1.8.22-gradle71-javadoc.jar",
          "size": 261,
          "sha512": "747d2f00a7f5f379582e33e452f30f3a25732a510971d9ed5161355bf7ef0fc507fef30883960dbfc780d36b6e8215fba01086b4ee053358805686e2f2c1aa85",
          "sha256": "69e1a62e5752ca3f43fb1607f161379bbe88b64af89c1a543c126160adf7cc53",
          "sha1": "5b8f86fea035328fc9e8c660773037a3401ce25f",
          "md5": "e7e9f45eb9d74540092920528bb0abf0"
        }
      ],
      "capabilities": [
        {
          "group": "org.jetbrains.kotlin",
          "name": "kotlin-gradle-plugin-model-gradle71",
          "version": "1.8.22"
        }
      ]
    },
    {
      "name": "gradle71SourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.plugin.api-version": "7.1",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "kotlin-gradle-plugin-model-1.8.22-gradle71-sources.jar",
          "url": "kotlin-gradle-plugin-model-1.8.22-gradle71-sources.jar",
          "size": 7932,
          "sha512": "33d5022df714168fb55a4745c47021948968b3123609f90c9e3659780b7c7387d4eb6a3f269c8b43438865ad7d581676952a90747b161b8135fe69015870a9e7",
          "sha256": "368bbe11831a72ba9df33f9c03c7795c967eace2bcfad0c91d406e2d9d494cd8",
          "sha1": "3eedaa08194a420cd2115833b92c97341b6aff48",
          "md5": "43536e5d73845058643dd884799797ce"
        }
      ],
      "capabilities": [
        {
          "group": "org.jetbrains.kotlin",
          "name": "kotlin-gradle-plugin-model-gradle71",
          "version": "1.8.22"
        }
      ]
    },
    {
      "name": "gradle71ApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.plugin.api-version": "7.1",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin-api",
          "version": {
            "requires": "1.8.22"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-reflect"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-script-runtime"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ],
          "requestedCapabilities": [
            {
              "group": "org.jetbrains.kotlin",
              "name": "kotlin-gradle-plugin-api-gradle71"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "kotlin-gradle-plugin-model-1.8.22-gradle71.jar",
          "url": "kotlin-gradle-plugin-model-1.8.22-gradle71.jar",
          "size": 12803,
          "sha512": "2d07f4b5d0fa8a160bce7b1060766145ff18c8fe057fe6e2b346edca2399ce653670cd787f15518ed9e265fdd569d1be3611e7334079f47ba7fc4064fd58f3fb",
          "sha256": "771d4ac928f422e43cf7ec067bbea337a0d2edf146389b65dda65df6d2d6e54a",
          "sha1": "3607c42ee2a7b827e978906ffc26f34c5241ae91",
          "md5": "1d16d30fc52cc0e088d47c0f15fd5fda"
        }
      ],
      "capabilities": [
        {
          "group": "org.jetbrains.kotlin",
          "name": "kotlin-gradle-plugin-model-gradle71",
          "version": "1.8.22"
        }
      ]
    },
    {
      "name": "gradle71RuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.plugin.api-version": "7.1",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin-api",
          "version": {
            "requires": "1.8.22"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-reflect"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-script-runtime"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ],
          "requestedCapabilities": [
            {
              "group": "org.jetbrains.kotlin",
              "name": "kotlin-gradle-plugin-api-gradle71"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "kotlin-gradle-plugin-model-1.8.22-gradle71.jar",
          "url": "kotlin-gradle-plugin-model-1.8.22-gradle71.jar",
          "size": 12803,
          "sha512": "2d07f4b5d0fa8a160bce7b1060766145ff18c8fe057fe6e2b346edca2399ce653670cd787f15518ed9e265fdd569d1be3611e7334079f47ba7fc4064fd58f3fb",
          "sha256": "771d4ac928f422e43cf7ec067bbea337a0d2edf146389b65dda65df6d2d6e54a",
          "sha1": "3607c42ee2a7b827e978906ffc26f34c5241ae91",
          "md5": "1d16d30fc52cc0e088d47c0f15fd5fda"
        }
      ],
      "capabilities": [
        {
          "group": "org.jetbrains.kotlin",
          "name": "kotlin-gradle-plugin-model-gradle71",
          "version": "1.8.22"
        }
      ]
    },
    {
      "name": "gradle74JavadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.plugin.api-version": "7.4",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "kotlin-gradle-plugin-model-1.8.22-gradle74-javadoc.jar",
          "url": "kotlin-gradle-plugin-model-1.8.22-gradle74-javadoc.jar",
          "size": 261,
          "sha512": "747d2f00a7f5f379582e33e452f30f3a25732a510971d9ed5161355bf7ef0fc507fef30883960dbfc780d36b6e8215fba01086b4ee053358805686e2f2c1aa85",
          "sha256": "69e1a62e5752ca3f43fb1607f161379bbe88b64af89c1a543c126160adf7cc53",
          "sha1": "5b8f86fea035328fc9e8c660773037a3401ce25f",
          "md5": "e7e9f45eb9d74540092920528bb0abf0"
        }
      ],
      "capabilities": [
        {
          "group": "org.jetbrains.kotlin",
          "name": "kotlin-gradle-plugin-model-gradle74",
          "version": "1.8.22"
        }
      ]
    },
    {
      "name": "gradle74SourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.plugin.api-version": "7.4",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "kotlin-gradle-plugin-model-1.8.22-gradle74-sources.jar",
          "url": "kotlin-gradle-plugin-model-1.8.22-gradle74-sources.jar",
          "size": 7932,
          "sha512": "33d5022df714168fb55a4745c47021948968b3123609f90c9e3659780b7c7387d4eb6a3f269c8b43438865ad7d581676952a90747b161b8135fe69015870a9e7",
          "sha256": "368bbe11831a72ba9df33f9c03c7795c967eace2bcfad0c91d406e2d9d494cd8",
          "sha1": "3eedaa08194a420cd2115833b92c97341b6aff48",
          "md5": "43536e5d73845058643dd884799797ce"
        }
      ],
      "capabilities": [
        {
          "group": "org.jetbrains.kotlin",
          "name": "kotlin-gradle-plugin-model-gradle74",
          "version": "1.8.22"
        }
      ]
    },
    {
      "name": "gradle74ApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.plugin.api-version": "7.4",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin-api",
          "version": {
            "requires": "1.8.22"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-reflect"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-script-runtime"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ],
          "requestedCapabilities": [
            {
              "group": "org.jetbrains.kotlin",
              "name": "kotlin-gradle-plugin-api-gradle74"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "kotlin-gradle-plugin-model-1.8.22-gradle74.jar",
          "url": "kotlin-gradle-plugin-model-1.8.22-gradle74.jar",
          "size": 12803,
          "sha512": "2d07f4b5d0fa8a160bce7b1060766145ff18c8fe057fe6e2b346edca2399ce653670cd787f15518ed9e265fdd569d1be3611e7334079f47ba7fc4064fd58f3fb",
          "sha256": "771d4ac928f422e43cf7ec067bbea337a0d2edf146389b65dda65df6d2d6e54a",
          "sha1": "3607c42ee2a7b827e978906ffc26f34c5241ae91",
          "md5": "1d16d30fc52cc0e088d47c0f15fd5fda"
        }
      ],
      "capabilities": [
        {
          "group": "org.jetbrains.kotlin",
          "name": "kotlin-gradle-plugin-model-gradle74",
          "version": "1.8.22"
        }
      ]
    },
    {
      "name": "gradle74RuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.plugin.api-version": "7.4",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin-api",
          "version": {
            "requires": "1.8.22"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-reflect"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-script-runtime"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ],
          "requestedCapabilities": [
            {
              "group": "org.jetbrains.kotlin",
              "name": "kotlin-gradle-plugin-api-gradle74"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "kotlin-gradle-plugin-model-1.8.22-gradle74.jar",
          "url": "kotlin-gradle-plugin-model-1.8.22-gradle74.jar",
          "size": 12803,
          "sha512": "2d07f4b5d0fa8a160bce7b1060766145ff18c8fe057fe6e2b346edca2399ce653670cd787f15518ed9e265fdd569d1be3611e7334079f47ba7fc4064fd58f3fb",
          "sha256": "771d4ac928f422e43cf7ec067bbea337a0d2edf146389b65dda65df6d2d6e54a",
          "sha1": "3607c42ee2a7b827e978906ffc26f34c5241ae91",
          "md5": "1d16d30fc52cc0e088d47c0f15fd5fda"
        }
      ],
      "capabilities": [
        {
          "group": "org.jetbrains.kotlin",
          "name": "kotlin-gradle-plugin-model-gradle74",
          "version": "1.8.22"
        }
      ]
    },
    {
      "name": "gradle75JavadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.plugin.api-version": "7.5",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "kotlin-gradle-plugin-model-1.8.22-gradle75-javadoc.jar",
          "url": "kotlin-gradle-plugin-model-1.8.22-gradle75-javadoc.jar",
          "size": 261,
          "sha512": "747d2f00a7f5f379582e33e452f30f3a25732a510971d9ed5161355bf7ef0fc507fef30883960dbfc780d36b6e8215fba01086b4ee053358805686e2f2c1aa85",
          "sha256": "69e1a62e5752ca3f43fb1607f161379bbe88b64af89c1a543c126160adf7cc53",
          "sha1": "5b8f86fea035328fc9e8c660773037a3401ce25f",
          "md5": "e7e9f45eb9d74540092920528bb0abf0"
        }
      ],
      "capabilities": [
        {
          "group": "org.jetbrains.kotlin",
          "name": "kotlin-gradle-plugin-model-gradle75",
          "version": "1.8.22"
        }
      ]
    },
    {
      "name": "gradle75SourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.plugin.api-version": "7.5",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "kotlin-gradle-plugin-model-1.8.22-gradle75-sources.jar",
          "url": "kotlin-gradle-plugin-model-1.8.22-gradle75-sources.jar",
          "size": 7932,
          "sha512": "33d5022df714168fb55a4745c47021948968b3123609f90c9e3659780b7c7387d4eb6a3f269c8b43438865ad7d581676952a90747b161b8135fe69015870a9e7",
          "sha256": "368bbe11831a72ba9df33f9c03c7795c967eace2bcfad0c91d406e2d9d494cd8",
          "sha1": "3eedaa08194a420cd2115833b92c97341b6aff48",
          "md5": "43536e5d73845058643dd884799797ce"
        }
      ],
      "capabilities": [
        {
          "group": "org.jetbrains.kotlin",
          "name": "kotlin-gradle-plugin-model-gradle75",
          "version": "1.8.22"
        }
      ]
    },
    {
      "name": "gradle75ApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.plugin.api-version": "7.5",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin-api",
          "version": {
            "requires": "1.8.22"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-reflect"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-script-runtime"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ],
          "requestedCapabilities": [
            {
              "group": "org.jetbrains.kotlin",
              "name": "kotlin-gradle-plugin-api-gradle75"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "kotlin-gradle-plugin-model-1.8.22-gradle75.jar",
          "url": "kotlin-gradle-plugin-model-1.8.22-gradle75.jar",
          "size": 12803,
          "sha512": "2d07f4b5d0fa8a160bce7b1060766145ff18c8fe057fe6e2b346edca2399ce653670cd787f15518ed9e265fdd569d1be3611e7334079f47ba7fc4064fd58f3fb",
          "sha256": "771d4ac928f422e43cf7ec067bbea337a0d2edf146389b65dda65df6d2d6e54a",
          "sha1": "3607c42ee2a7b827e978906ffc26f34c5241ae91",
          "md5": "1d16d30fc52cc0e088d47c0f15fd5fda"
        }
      ],
      "capabilities": [
        {
          "group": "org.jetbrains.kotlin",
          "name": "kotlin-gradle-plugin-model-gradle75",
          "version": "1.8.22"
        }
      ]
    },
    {
      "name": "gradle75RuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.plugin.api-version": "7.5",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin-api",
          "version": {
            "requires": "1.8.22"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-reflect"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-script-runtime"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ],
          "requestedCapabilities": [
            {
              "group": "org.jetbrains.kotlin",
              "name": "kotlin-gradle-plugin-api-gradle75"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "kotlin-gradle-plugin-model-1.8.22-gradle75.jar",
          "url": "kotlin-gradle-plugin-model-1.8.22-gradle75.jar",
          "size": 12803,
          "sha512": "2d07f4b5d0fa8a160bce7b1060766145ff18c8fe057fe6e2b346edca2399ce653670cd787f15518ed9e265fdd569d1be3611e7334079f47ba7fc4064fd58f3fb",
          "sha256": "771d4ac928f422e43cf7ec067bbea337a0d2edf146389b65dda65df6d2d6e54a",
          "sha1": "3607c42ee2a7b827e978906ffc26f34c5241ae91",
          "md5": "1d16d30fc52cc0e088d47c0f15fd5fda"
        }
      ],
      "capabilities": [
        {
          "group": "org.jetbrains.kotlin",
          "name": "kotlin-gradle-plugin-model-gradle75",
          "version": "1.8.22"
        }
      ]
    },
    {
      "name": "gradle76JavadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.plugin.api-version": "7.6",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "kotlin-gradle-plugin-model-1.8.22-gradle76-javadoc.jar",
          "url": "kotlin-gradle-plugin-model-1.8.22-gradle76-javadoc.jar",
          "size": 261,
          "sha512": "747d2f00a7f5f379582e33e452f30f3a25732a510971d9ed5161355bf7ef0fc507fef30883960dbfc780d36b6e8215fba01086b4ee053358805686e2f2c1aa85",
          "sha256": "69e1a62e5752ca3f43fb1607f161379bbe88b64af89c1a543c126160adf7cc53",
          "sha1": "5b8f86fea035328fc9e8c660773037a3401ce25f",
          "md5": "e7e9f45eb9d74540092920528bb0abf0"
        }
      ],
      "capabilities": [
        {
          "group": "org.jetbrains.kotlin",
          "name": "kotlin-gradle-plugin-model-gradle76",
          "version": "1.8.22"
        }
      ]
    },
    {
      "name": "gradle76SourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.plugin.api-version": "7.6",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "kotlin-gradle-plugin-model-1.8.22-gradle76-sources.jar",
          "url": "kotlin-gradle-plugin-model-1.8.22-gradle76-sources.jar",
          "size": 7932,
          "sha512": "33d5022df714168fb55a4745c47021948968b3123609f90c9e3659780b7c7387d4eb6a3f269c8b43438865ad7d581676952a90747b161b8135fe69015870a9e7",
          "sha256": "368bbe11831a72ba9df33f9c03c7795c967eace2bcfad0c91d406e2d9d494cd8",
          "sha1": "3eedaa08194a420cd2115833b92c97341b6aff48",
          "md5": "43536e5d73845058643dd884799797ce"
        }
      ],
      "capabilities": [
        {
          "group": "org.jetbrains.kotlin",
          "name": "kotlin-gradle-plugin-model-gradle76",
          "version": "1.8.22"
        }
      ]
    },
    {
      "name": "gradle76ApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.plugin.api-version": "7.6",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin-api",
          "version": {
            "requires": "1.8.22"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-reflect"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-script-runtime"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ],
          "requestedCapabilities": [
            {
              "group": "org.jetbrains.kotlin",
              "name": "kotlin-gradle-plugin-api-gradle76"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "kotlin-gradle-plugin-model-1.8.22-gradle76.jar",
          "url": "kotlin-gradle-plugin-model-1.8.22-gradle76.jar",
          "size": 12803,
          "sha512": "2d07f4b5d0fa8a160bce7b1060766145ff18c8fe057fe6e2b346edca2399ce653670cd787f15518ed9e265fdd569d1be3611e7334079f47ba7fc4064fd58f3fb",
          "sha256": "771d4ac928f422e43cf7ec067bbea337a0d2edf146389b65dda65df6d2d6e54a",
          "sha1": "3607c42ee2a7b827e978906ffc26f34c5241ae91",
          "md5": "1d16d30fc52cc0e088d47c0f15fd5fda"
        }
      ],
      "capabilities": [
        {
          "group": "org.jetbrains.kotlin",
          "name": "kotlin-gradle-plugin-model-gradle76",
          "version": "1.8.22"
        }
      ]
    },
    {
      "name": "gradle76RuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.plugin.api-version": "7.6",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin-api",
          "version": {
            "requires": "1.8.22"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-reflect"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-script-runtime"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ],
          "requestedCapabilities": [
            {
              "group": "org.jetbrains.kotlin",
              "name": "kotlin-gradle-plugin-api-gradle76"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "kotlin-gradle-plugin-model-1.8.22-gradle76.jar",
          "url": "kotlin-gradle-plugin-model-1.8.22-gradle76.jar",
          "size": 12803,
          "sha512": "2d07f4b5d0fa8a160bce7b1060766145ff18c8fe057fe6e2b346edca2399ce653670cd787f15518ed9e265fdd569d1be3611e7334079f47ba7fc4064fd58f3fb",
          "sha256": "771d4ac928f422e43cf7ec067bbea337a0d2edf146389b65dda65df6d2d6e54a",
          "sha1": "3607c42ee2a7b827e978906ffc26f34c5241ae91",
          "md5": "1d16d30fc52cc0e088d47c0f15fd5fda"
        }
      ],
      "capabilities": [
        {
          "group": "org.jetbrains.kotlin",
          "name": "kotlin-gradle-plugin-model-gradle76",
          "version": "1.8.22"
        }
      ]
    }
  ]
}
