// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdzPcogqmfNxWcS5sEUs2vzneD8tRYRVU',
    appId: '1:761758829736:web:0392aa7d6183e472dc069d',
    messagingSenderId: '761758829736',
    projectId: 'hoopslab-v1',
    authDomain: 'hoopslab-v1.firebaseapp.com',
    storageBucket: 'hoopslab-v1.firebasestorage.app',
    measurementId: 'G-2C1HPDT6F7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUec81SMycRFBNvzddWffcOLPHkF3YJyU',
    appId: '1:761758829736:android:40e73c7ccbdf29bbdc069d',
    messagingSenderId: '761758829736',
    projectId: 'hoopslab-v1',
    storageBucket: 'hoopslab-v1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVg2vbI2ns7lljJAi-xIPIs6EsCTCGypc',
    appId: '1:761758829736:ios:390c1bc943bfb169dc069d',
    messagingSenderId: '761758829736',
    projectId: 'hoopslab-v1',
    storageBucket: 'hoopslab-v1.firebasestorage.app',
    iosBundleId: 'com.example.hoopsLabV1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAVg2vbI2ns7lljJAi-xIPIs6EsCTCGypc',
    appId: '1:761758829736:ios:390c1bc943bfb169dc069d',
    messagingSenderId: '761758829736',
    projectId: 'hoopslab-v1',
    storageBucket: 'hoopslab-v1.firebasestorage.app',
    iosBundleId: 'com.example.hoopsLabV1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBdzPcogqmfNxWcS5sEUs2vzneD8tRYRVU',
    appId: '1:761758829736:web:1faab7236525db11dc069d',
    messagingSenderId: '761758829736',
    projectId: 'hoopslab-v1',
    authDomain: 'hoopslab-v1.firebaseapp.com',
    storageBucket: 'hoopslab-v1.firebasestorage.app',
    measurementId: 'G-SZ7V3G2JZG',
  );

}