{
  "formatVersion": "1.1",
  "component": {
    "url": "../../mockk-core/1.13.16/mockk-core-1.13.16.module",
    "group": "io.mockk",
    "module": "mockk-core",
    "version": "1.13.16",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.1"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "mockk-core-jvm-1.13.16.jar",
          "url": "mockk-core-jvm-1.13.16.jar",
          "size": 5120,
          "sha512": "db6b211f9020cec8d3608a4961f93425ae92beabb17fc1c07ba6eff73bafd2c9e019adbc32e3f562ac8dfa61665e37fb6dbee027700310ebd311d7d82a66324d",
          "sha256": "0d759240d7ba8cde6edd84c947a0ad7dcf7675bbeb348560f5e7a0cc61629df8",
          "sha1": "390bc1d0d93833980df0f0f4821ae92ab9d650ba",
          "md5": "3054b47f590555fcd17efbda0cdee825"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "mockk-core-jvm-1.13.16.jar",
          "url": "mockk-core-jvm-1.13.16.jar",
          "size": 5120,
          "sha512": "db6b211f9020cec8d3608a4961f93425ae92beabb17fc1c07ba6eff73bafd2c9e019adbc32e3f562ac8dfa61665e37fb6dbee027700310ebd311d7d82a66324d",
          "sha256": "0d759240d7ba8cde6edd84c947a0ad7dcf7675bbeb348560f5e7a0cc61629df8",
          "sha1": "390bc1d0d93833980df0f0f4821ae92ab9d650ba",
          "md5": "3054b47f590555fcd17efbda0cdee825"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "mockk-core-jvm-1.13.16-sources.jar",
          "url": "mockk-core-jvm-1.13.16-sources.jar",
          "size": 3323,
          "sha512": "2d1d2acf85e1d6d5c8145321fc20631766430d20f9e4e9985b71d013a308afe22da351439eab8c8ce0b9fc955f72d2469f242c3b11bd2b3ab434a649b059f39b",
          "sha256": "d52a47e9d61416052ac8a9039f9c21114daf1e3cebe34645242abfdc8e832517",
          "sha1": "393beea67cf50c88a09f5ee5ea84fd937ac79cde",
          "md5": "78c2a0eb265876c7551b56de213d2baf"
        }
      ]
    }
  ]
}
