{
  "formatVersion": "1.1",
  "component": {
    "group": "org.robolectric",
    "module": "sandbox",
    "version": "4.12.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.robolectric",
          "module": "annotations",
          "version": {
            "requires": "4.12.1"
          }
        },
        {
          "group": "org.robolectric",
          "module": "utils",
          "version": {
            "requires": "4.12.1"
          }
        },
        {
          "group": "org.robolectric",
          "module": "shadowapi",
          "version": {
            "requires": "4.12.1"
          }
        },
        {
          "group": "org.robolectric",
          "module": "utils-reflector",
          "version": {
            "requires": "4.12.1"
          }
        },
        {
          "group": "javax.annotation",
          "module": "javax.annotation-api",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "javax.inject",
          "module": "javax.inject",
          "version": {
            "requires": "1"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.7"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.7"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "31.1-jre"
          }
        }
      ],
      "files": [
        {
          "name": "sandbox-4.12.1.jar",
          "url": "sandbox-4.12.1.jar",
          "size": 135451,
          "sha512": "2d322139d347e9f4d82da9cba692cd9e004e77e7b8a3c0dd2097752f96a846cb97252239b7f7b19e71e2cd8da17f79e787a95fda48ea9830edc9bb2bf69fe17d",
          "sha256": "30bf063d2cf43b3728559e16f75bf21b6e333910965fd4f102105107d4c0913f",
          "sha1": "1fe092b79e6d6d487e996de4adc3a3e239cbfa09",
          "md5": "c72a1ef101dafffeb84ecc1c906213c6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.robolectric",
          "module": "annotations",
          "version": {
            "requires": "4.12.1"
          }
        },
        {
          "group": "org.robolectric",
          "module": "utils",
          "version": {
            "requires": "4.12.1"
          }
        },
        {
          "group": "org.robolectric",
          "module": "shadowapi",
          "version": {
            "requires": "4.12.1"
          }
        },
        {
          "group": "org.robolectric",
          "module": "utils-reflector",
          "version": {
            "requires": "4.12.1"
          }
        },
        {
          "group": "javax.annotation",
          "module": "javax.annotation-api",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "javax.inject",
          "module": "javax.inject",
          "version": {
            "requires": "1"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.7"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.7"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "31.1-jre"
          }
        }
      ],
      "files": [
        {
          "name": "sandbox-4.12.1.jar",
          "url": "sandbox-4.12.1.jar",
          "size": 135451,
          "sha512": "2d322139d347e9f4d82da9cba692cd9e004e77e7b8a3c0dd2097752f96a846cb97252239b7f7b19e71e2cd8da17f79e787a95fda48ea9830edc9bb2bf69fe17d",
          "sha256": "30bf063d2cf43b3728559e16f75bf21b6e333910965fd4f102105107d4c0913f",
          "sha1": "1fe092b79e6d6d487e996de4adc3a3e239cbfa09",
          "md5": "c72a1ef101dafffeb84ecc1c906213c6"
        }
      ]
    }
  ]
}
